# Generated by Django 3.1.3 on 2020-11-24 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavingmessage',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
