# Generated by Django 3.1.3 on 2020-12-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[(False, '未请假'), (True, '请假中')], default=False, verbose_name='休假状态'),
        ),
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256, verbose_name='请假原因')),
                ('status', models.BooleanField(choices=[(False, '审核中'), (True, '已批准')], null=True)),
                ('applydate', models.DateTimeField(auto_now_add=True, verbose_name='申请日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user', verbose_name='用户')),
            ],
        ),
    ]
